### ISSUE TITLE
B13.0 Deployment Build and Updates

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#40]
- [x] Update latest software release on nasa-pds.github.io

- [x] Discipline LDD Release
   - [x] [Stage LDD Release](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-StageLDDRelease)
   - [x] [Post Release Updates](https://wiki.jpl.nasa.gov/display/PDSEN/dLDD+Release+Procedures#dLDDReleaseProcedures-PostReleaseUpdates)
   - [x] Post updates to [dd-library](https://github.com/pds-data-dictionaries/dd-library/) github per https://github.com/pds-data-dictionaries/dd-library/issues/1 and update procedures accordingly

- [x] Deployment Updates Needed
    - [x] TBD DOI Deployment Updates per Cognito (@ramesh-maddegoda to provide detail)
    - [x] Update all node cloud registry services to new version
       - [x] Place updated CloudFront function which removes minor version from requests (e.g. 1.0 -> 1)
       - [x] Update all load balancer routing rules to process major version only requests (via terraform)
       - [x] Build/upload service version to ECS
       - [x] Re-run terraform scripts to place update service ECS images
    - [x] Add routing rule for 1.1 documentation 

- [x] Deployment on gamma
     - [x] loader/manager (@c-suh )
     - [x] validate (@c-suh )

- [x] Deployment of Operational Environment
    - Registry components
      - [x] Patched Services v1.1.12 (Jimmie) 
      - [x] loader/manager (@c-suh )
  
(for now we still use validate on gamma for production actitities related to NSSDCA)
  

- [x] Webpage Updated
   - [x] [Stage IM Release](https://wiki.jpl.nasa.gov/display/PDSEN/PDS4+IM+Release#PDS4IMRelease-StageRelease)
   - [x] Update WebHelp
   - [x] Update TBD web pages

**Comment by jordanpadams** [comment]
blocked by not being ready, but keeping in sprint backlog so we are all aware of it's existence

**Comment by ramesh-maddegoda** [comment]
## The deployment activities specific to the Cognito authentication of **doi-ui** and **doi-service** 

### doi-ui - Cognito Specific deployment activities
To deploy that doi-ui AWS cloud, we have make sure (request relevant Sys Admin team) to,
1. Create 2 Cognito user groups in that user pool called,
          - PDS_Viewer
          - PDS_Admin
2. Share the Cognito client ID of the Cognito App client which is used by doi-ui with our team
3. Share the Cognito domain name with our team
4. Update the config file: https://github.com/NASA-PDS/doi-ui/blob/main/public/config.js before deployment with the <CLIENT ID OF COGNITO APP CLIENT> and <COGNITO DOMAIN NAME>
5. Deploy doi-ui 
6. Add our users (JPL SSO users) to the above created 2 user groups PDS_Viewer and PDS_Admin as appropriate. (the user should try to login to the doi-ui once before adding the user, so there will be a JPL SSO user record in Cognito pool)
7. In Cognito user pool,  click on the user name and then add user to new user groups (PDS_Viewer and/or PDS_Admin).
8. After that, ask users to access doi-ui with JPL SSO (should be successful)


### doi-service - Cognito Specific deployment activities
1. The required configs are documented in https://github.com/NASA-PDS/doi-service README. We should update the following section of the doi-service configurations with,
-  AWS Region `<aws-region>`
-  Cognito user pool ID `<userpoolID>`

```
[API_AUTHENTICATION]
# Add the issuer of the oauth tokens, for cognito https://cognito-idp.<aws-region>.amazonaws.com/<userpoolID>
jwt_issuer =
# Add the entire content of the JSON file at https://cognito-idp.<aws-region>.amazonaws.com/<userpoolID>/.well-known/jwks.json
json_web_key_set =
jwt_lifetime_seconds = 3600
jwt_algorithm = RS256 
```

**Comment by ramesh-maddegoda** [comment]
Updated the deployment wiki pages.

(1) doi-ui cognito deployment (wiki):
https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=668962936
(2) doi-service cognito deployment(wiki):
https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=668962954

**Comment by tloubrieu-jpl** [comment]
Thanks @ramesh-maddegoda 
Should the new pages be eventually integrated with the existing deployment procedures for the doi service and ui and should they replace them ?

**Comment by ramesh-maddegoda** [comment]
> Thanks @ramesh-maddegoda Should the new pages be eventually integrated with the existing deployment procedures for the doi service and ui and should they replace them ?

@tloubrieu-jpl , the wiki pages were only for Cognito specific deployment configs. I think those should be eventually be part of a doi deployment document.

**Comment by tloubrieu-jpl** [comment]
Thanks @ramesh-maddegoda , we can validate with @c-suh and the rest of the group that it should be integrated with in the standard deployment pages at a next stand up /break out and then do it.

**Comment by c-suh** [comment]
Discipline LDD and page updates to be released this Friday on December 2nd. @jordanpadams, @viviant100, and @tloubrieu-jpl anything for the "TBD components to deploy" (from the middle of the [description above](https://github.com/NASA-PDS/software-issues-repo/issues/40#issue-1382774425))?

**Comment by c-suh** [comment]
Hit a snag with "No space left on device" and have opened [a ticket](https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-3052) with the SAs. Will work on other steps, i.e. updating site pages for documents, while this is worked out.

**Comment by c-suh** [comment]
@viviant100 the LDDs have been released at https://pds.nasa.gov/datastandards/dictionaries/ and all documents but one have been updated at https://pds.nasa.gov/datastandards/documents/. The last document is the webhelp version of all data dictionaries, which Steve generates once I release the LDDs and send him certain files. I sent those files to him today after releasing the LDDs and will upload them once he has them ready!

**Comment by c-suh** [comment]
@viviant100 (apologies I forgot to update this yesterday) the last of the webhelp files have been uploaded and all tasks for "Discipline LDD Release" and "Webpage Updated" are complete!

**Comment by viviant100** [comment]
thanks @c-suh!

**Comment by jimmie** [comment]
I am planning on placing the update CloudFront function and updating load balancer routing rules this evening (Monday, 12/12) during off hours. This will enable updates to the service to be transparent to users and DNs.

Resharding will occur this week (week of 12/12).

**Comment by jimmie** [comment]
A DSIO ticket has been created to have the documentation redirect rule added to the load balancer: https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-3114 since we mere mortals cannot manually create rules (only through terraform).

**Comment by tloubrieu-jpl** [comment]
The preparation of a stable release for DOI is blocked by ticket https://github.com/NASA-PDS/doi-ui/issues/178

**Comment by tloubrieu-jpl** [comment]
These tasks have been removed before of other bugs found on the doi-service/ui:
- [ ] Deployment of Staging Environment (gamma)
    - [ ] DOI Service w/ crontab update (@c-suh )
    - [ ] DOI Editor (not ready) (@c-suh )

In production:
    -  [ ] DOI Service w/ crontab update (@c-suh )
    - [ ] DOI Editor (not ready) (@c-suh )

**Comment by c-suh** [comment]
Registry Manager v4.5.4, Standalone Harvest v3.7.4, and Validate v3.3.1 are deployed on gamma and awaiting tests from RChen.

**Comment by jordanpadams** [comment]
I think we can call this good and re-open if we run into any issues

**Comment by jimmie** [comment]
Closing per Jordan's comment
