### ISSUE TITLE
Switchover from PDS JIRA to Private GitHub for PDS4 SCR Management

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/PDS-Software-Issues-Repo#67]
## 💡 Description

Timeline:
- [X] 12/20/23 (today) – GitHub repo is live and ready for new tickets
- [x] 01/05/24 – pds-jira site frozen as read-only to begin archiving process for existing tickets.
- [x] 01/12/24 – complete archiving to JIRA cloud
  - https://github.com/NASA-PDS/software-issues-repo/issues/70
- [x] 01/19/24 – complete testing of JIRA cloud, and shutdown pds-jira
  - https://github.com/NASA-PDS/software-issues-repo/issues/69 

Other Sub-tasks:
- https://github.com/NASA-PDS/software-issues-repo/issues/68

**Comment by jordanpadams** [comment]
📆 April status: URS submitted. Awaiting JPL Cyber review and approval of Atlassian JIRA SaaS. No impact on build. License does not expire for several months

**Comment by jordanpadams** [comment]
📆 May status: Delayed due to delay in URS approval. No impact on build

**Comment by jordanpadams** [comment]
📆 June status: Open source route will not work. New license procurement underway. On schedule, but not required for B14.0 delivery.

**Comment by jordanpadams** [comment]
📆 July status: Move scheduled for September. Deferred to B14.1 Plan. Not required for B14.0

**Comment by jordanpadams** [comment]
📆 October status: Awaiting decision from DDWG / CCB / MC on where to go with this. On schedule

**Comment by jordanpadams** [comment]
📆 November status: MC decided on private GitHub repo for future issue management. Migration underway. On schedule.

**Comment by jordanpadams** [comment]
All sub-tasks completed. New repo ready for SCRs. https://github.com/NASA-PDS/PDS4-CCB/. Past JIRA tickets archived at https://nasa-pds.atlassian.net/jira/software/c/projects/CCB/
